MFD Color and Sizing Changes
Working-Title-MSFS-Mods/fspackages pull request #364
Opened 2020-10-22 22:21 UTC by K20017

Changed the sizing, font colors, and positioning of text on the MFD systems readouts and SYS overlays.  I also added a fake needle for oxygen pressure at 1800. Would never really move in the real world so no reason for it not to be anything other than the normal position.

2020-10-22 22:35 UTC, dga711 requested changes

2020-10-22 22:35 UTC, dga711 commented on src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
> +                let BatVolt = SimVar.GetSimVarValue("ELECTRICAL BATTERY VOLTAGE:1", "volts");
this reverts battery fix

2020-10-22 22:35 UTC, dga711 commented on src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/MFD/CJ4_MFD.js
> -
kills matts map

2020-10-22 22:35 UTC, dga711 commented on src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/Shared/CJ4_Shared.js
> +        let BatVolt = SimVar.GetSimVarValue("ELECTRICAL BATTERY VOLTAGE:1", "volts");
reverts battery watt/amp changes

2020-10-23 00:53 UTC, mattnischan approved these changes

2020-10-23 07:16 UTC, dga711 approved these changes

2020-10-23 07:17 UTC, merged